### PR TITLE
Fix plugin repository for mavenLocal

### PR DESCRIPTION
**Pull request by snowe2010**

### CODE REVIEW

**Comment by henrik242** [comment]
Thanks!

**Comment by henrik242** [comment]
@snowe2010 Somehow your patch didn't work for me (while it works for me without the patch).   Any ideas why?

**Comment by snowe2010** [comment]
you'll need to comment out the plugin declaration first, publish to maven local, and then uncomment the plugin description. It can't publish unless it can build, and it can't build because it can't find the plugin.

**Comment by henrik242** [comment]
I did that without success.  But that's a thing of the past now, since I've switched to `GradleRunner` :)

**Pull request merged**
